/**
 * Waveform — SoundCloud-style audio waveform visualization.
 *
 * Renders pre-computed peaks (generated by `ghost-backend/scripts/generate-peaks.js`
 * and stored on R2 next to each MP3 as `audio/<name>.peaks.json`).
 *
 * Why custom SVG instead of wavesurfer.js: we ALREADY have the peaks JSON +
 * the audio playback engine (single shared <audio> element in ShopPlayerContext).
 * All wavesurfer would buy us is the renderer — at the cost of trying to sync
 * its internal audio with our external one. Custom SVG is ~50 LOC, lighter,
 * 100% controllable colors.
 *
 * Interaction (click/drag-to-seek) is intentionally NOT inside this component.
 * The parent attaches its own ref + onMouseDown/onTouchStart to the wrapping
 * div, so this stays a pure visualizer. ShopStickyPlayer keeps its existing
 * scrub logic.
 *
 * Caching: peaks JSON is fetched once per audioUrl per page session. Same
 * track viewed twice = zero network hits.
 *
 * Fallback: while peaks load (or if the .peaks.json is missing — older tracks,
 * etc.), we draw a thin flat progress bar so the UI never looks broken.
 */
import React, { useEffect, useState } from "react";

const CYAN = "#00E5FF";
const PURPLE = "#BB86FC";

// Module-scoped cache — survives component remount during navigation.
// Values are Promises so concurrent calls share the same fetch.
const peaksCache = new Map();

function fetchPeaks(peaksUrl) {
  if (peaksCache.has(peaksUrl)) return peaksCache.get(peaksUrl);
  const p = fetch(peaksUrl)
    .then((r) => (r.ok ? r.json() : null))
    .then((j) => (j && Array.isArray(j.data) ? j.data : null))
    .catch(() => null);
  peaksCache.set(peaksUrl, p);
  return p;
}

/**
 * @param {string} audioUrl  Full MP3 URL — peaks URL is derived by .mp3 → .peaks.json
 * @param {number} progress  0..1 playback position (clamped internally)
 * @param {number} height    Display height in CSS px. SVG scales width via 100%.
 */
export default function Waveform({ audioUrl, progress = 0, height = 40 }) {
  const [peaks, setPeaks] = useState(null);

  useEffect(() => {
    if (!audioUrl) { setPeaks(null); return; }
    const peaksUrl = audioUrl.replace(/\.mp3(\?.*)?$/, ".peaks.json");
    let mounted = true;
    fetchPeaks(peaksUrl).then((p) => { if (mounted) setPeaks(p); });
    return () => { mounted = false; };
  }, [audioUrl]);

  const clampedProgress = Math.max(0, Math.min(1, progress));

  // Fallback bar — used while peaks load OR if peaks.json is missing.
  // Same height as the waveform so layout doesn't shift on arrival.
  if (!peaks || peaks.length === 0) {
    return (
      <div
        style={{
          width: "100%",
          height,
          position: "relative",
          display: "flex",
          alignItems: "center",
          pointerEvents: "none",
        }}
      >
        <div
          style={{
            width: "100%",
            height: 3,
            background: "rgba(255,255,255,0.12)",
            borderRadius: 2,
            position: "relative",
            overflow: "hidden",
          }}
        >
          <div
            style={{
              position: "absolute",
              top: 0, left: 0,
              height: "100%",
              width: `${clampedProgress * 100}%`,
              background: `linear-gradient(90deg, ${CYAN}, #00b8d4)`,
              transition: "width 0.1s linear",
            }}
          />
        </div>
      </div>
    );
  }

  const n = peaks.length;
  const h = height;
  const mid = h / 2;
  const progressIndex = Math.floor(clampedProgress * n);

  // Render each peak as a vertical bar centered vertically.
  // Played bars: solid cyan with glow. Unplayed: faded purple.
  return (
    <svg
      width="100%"
      height={h}
      viewBox={`0 0 ${n} ${h}`}
      preserveAspectRatio="none"
      style={{ pointerEvents: "none", display: "block" }}
      aria-hidden="true"
    >
      {peaks.map((p, i) => {
        // Each peak is 0..1. Min visible bar is 1px so silent regions still draw.
        const barH = Math.max(1, p * h * 0.92);
        const y = mid - barH / 2;
        const played = i < progressIndex;
        return (
          <rect
            key={i}
            x={i + 0.15}
            y={y}
            width={0.7}
            height={barH}
            fill={played ? CYAN : PURPLE}
            opacity={played ? 1 : 0.35}
          />
        );
      })}
    </svg>
  );
}
